version: '3'

services:

  timemanager-postgresql:
    image: postgres
    restart: always
    container_name: timemanager-postgresql
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432

  timemanager-back:
    image: openjdk:11
    container_name: timemanager-back
    depends_on:
      - timemanager-postgresql
    ports:
      - 4000:${BACKEND_APP_PORT}
    volumes:
      - ./timemanager-api/target/timemanager-api-0.0.1-SNAPSHOT.jar:/timemanager-api/timemanager-api-0.0.1-SNAPSHOT.jar
    command: ["java", "-Xmx8g", "-jar", "/timemanager-api/timemanager-api-0.0.1-SNAPSHOT.jar", "--server.port=${BACKEND_APP_PORT}", "--spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true", "--spring.datasource.username=${DATABASE_USER}", "--spring.datasource.password=${DATABASE_PASSWORD}", "--timemanager.global-manager.username=${GLOBAL_MANAGER_USERNAME}", "--timemanager.global-manager.email=${GLOBAL_MANAGER_EMAIL}", "--timemanager.global-manager.password=${GLOBAL_MANAGER_PASSWORD}"]
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - GLOBAL_MANAGER_USERNAME=${GLOBAL_MANAGER_USERNAME}
      - GLOBAL_MANAGER_EMAIL=${GLOBAL_MANAGER_EMAIL}
      - GLOBAL_MANAGER_PASSWORD=${GLOBAL_MANAGER_PASSWORD}