server:
  port: 4000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    configUrl: "/v3/api-docs/swagger-config"
    
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/timemanager"
    username: postgres
    password: postgres

jwt:
  secret: "c2VjcmV0X3Bhc3N3b3Jk"